[build]
  command = "npm run build"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; frame-ancestors 'self' https://plugins-cdn.datocms.com; script-src: 'self' 'unsafe-inline'; styles-src: 'self' 'unsafe-inline'"